#pragma once

//Player
#define PLAYER_HORIZONTAL_SPEED 5
#define PLAYER_VERTICAL_SPEED 2
#define PLAYER_COLLIDER_SIZE 100
#define PLAYER_SCALE 0.2f
#define PLAYER_INITIAL_POSITION_X 550
#define PLAYER_INITIAL_POSITION_Y 700

//Scene
#define MAIN_GAME_CAMERA_SPEED 2
